// team: abbreviation
export const TEAMS: Map<string, string> = new Map<string, string>([
    ["Arizona Cardinals", "ARI"],
    ["Los Angeles Rams", "LAR"],
    ["Kansas City Chiefs", "KC"],
    ["Cincinnati Bengals", "CIN"],
    ["Green Bay Packers", "GB"],
    ["San Francisco 49ers", "SF"],
    ["Tampa Bay Buccaneers", "TB"],
    ["Buffalo Bills", "BUF"],
    ["Dallas Cowboys", "DAL"],
    ["Los Angeles Chargers", "LAC"],
    ["Pittsburgh Steelers", "PIT"],
    ["Denver Broncos", "DEN"],
    ["Miami Dolphins", "MIA"],
    ["Minnesota Vikings", "MIN"],
    ["Chicago Bears", "CHI"],
    ["Detroit Lions", "DET"],
    ["Atlanta Falcons", "ATL"],
    ["Philadelphia Eagles", "PHI"],
    ["Seattle Seahawks", "SEA"],
    ["New England Patriots", "NE"],
    ["Indianapolis Colts", "IND"],
    ["Las Vegas Raiders", "LV"],
    ["Washington Football Team", "WFT"],
    ["New York Jets", "NYJ"],
    ["New Orleans Saints", "NO"],
    ["Baltimore Ravens", "BAL"],
    ["Jacksonville Jaguars", "JAX"],
    ["New York Giants", "NYG"],
    ["Tennessee Titans", "TEN"],
    ["Cleveland Browns", "CLE"],
    ["Houston Texans", "HOU"],
    ["Carolina Panthers", "CAR"],
    ["Phoenix Cardinals", "PHX"],
    ["Tennessee Oilers", "OIL"],
    ["Oakland Raiders", "OAK"],
    ["Los Angeles Raiders", "RAI"],
    ["St. Louis Rams", "STR"],
    ["Washington Commanders", "WAS"],
    ["San Diego Chargers", "SDC"]
]);

export const ABBREVIATION_TO_TEAM_MAP: Map<string, string> = new Map<string, string>([
    ["ARI", "Arizona Cardinals"],
    ["LAR", "Los Angeles Rams"],
    ["KC", "Kansas City Chiefs"],
    ["CIN", "Cincinnati Bengals"],
    ["GB", "Green Bay Packers"],
    ["SF", "San Francisco 49ers"],
    ["TB", "Tampa Bay Buccaneers"],
    ["BUF", "Buffalo Bills"],
    ["DAL", "Dallas Cowboys"],
    ["LAC", "Los Angeles Chargers"],
    ["PIT", "Pittsburgh Steelers"],
    ["DEN", "Denver Broncos"],
    ["MIA", "Miami Dolphins"],
    ["MIN", "Minnesota Vikings"],
    ["CHI", "Chicago Bears"],
    ["DET", "Detroit Lions"],
    ["ATL", "Atlanta Falcons"],
    ["PHI", "Philadelphia Eagles"],
    ["SEA", "Seattle Seahawks"],
    ["NE", "New England Patriots"],
    ["IND", "Indianapolis Colts"],
    ["LV", "Las Vegas Raiders"],
    ["WFT", "Washington Football Team"],
    ["NYJ", "New York Jets"],
    ["NO", "New Orleans Saints"],
    ["BAL", "Baltimore Ravens"],
    ["JAX", "Jacksonville Jaguars"],
    ["NYG", "New York Giants"],
    ["TEN", "Tennessee Titans"],
    ["CLE", "Cleveland Browns"],
    ["HOU", "Houston Texans"],
    ["CAR", "Carolina Panthers"],
    ["PHX", "Phoenix Cardinals"],
    ["OIL", "Tennessee Oilers"],
    ["OAK", "Oakland Raiders"],
    ["RAI", "Los Angeles Raiders"],
    ["STR", "St. Louis Rams"],
    ["WAS", "Washington Commanders"],
    ["SDC", "San Diego Chargers"]
]);