// team: abbreviation
export const TEAMS = new Map([
    ["Arizona Cardinals", "ARI"],
    ["Los Angeles Rams", "LAR"],
    ["Kansas City Chiefs", "KC"],
    ["Cincinnati Bengals", "CIN"],
    ["Green Bay Packers", "GB"],
    ["San Francisco 49ers", "SF"],
    ["Tampa Bay Buccaneers", "TB"],
    ["Buffalo Bills", "BUF"],
    ["Dallas Cowboys", "DAL"],
    ["Los Angeles Chargers", "LAC"],
    ["Pittsburgh Steelers", "PIT"],
    ["Denver Broncos", "DEN"],
    ["Miami Dolphins", "MIA"],
    ["Minnesota Vikings", "MIN"],
    ["Chicago Bears", "CHI"],
    ["Detroit Lions", "DET"],
    ["Atlanta Falcons", "ATL"],
    ["Philadelphia Eagles", "PHI"],
    ["Seattle Seahawks", "SEA"],
    ["New England Patriots", "NE"],
    ["Indianapolis Colts", "IND"],
    ["Las Vegas Raiders", "LV"],
    ["Washington Football Team", "WFT"],
    ["New York Jets", "NYJ"],
    ["New Orleans Saints", "NO"],
    ["Baltimore Ravens", "BAL"],
    ["Jacksonville Jaguars", "JAX"],
    ["New York Giants", "NYG"],
    ["Tennessee Titans", "TEN"],
    ["Cleveland Browns", "CLE"],
    ["Houston Texans", "HOU"],
    ["Carolina Panthers", "CAR"],
    ["Phoenix Cardinals", "PHX"],
    ["Tennessee Oilers", "OIL"],
    ["Oakland Raiders", "OAK"],
    ["Los Angeles Raiders", "RAI"]
]);